spring.application.name=ggstore-api

spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.dtudhbhgymaimhddyotx
spring.datasource.password=FQFqnoR17PONJji7
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

server.port=8080

jwt.secret=GGStore2026SecretKeyParaJWTMuyLargaYSeguraParaProduccion1234567890AbCdEfGhIjKlMnOp
jwt.expiration-ms=86400000

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

spring.datasource.hikari.connection-init-sql=SET search_path=public
spring.jpa.properties.hibernate.jdbc.use_get_generated_keys=false