spring.application.name=ggstore-api

# Conexion a Supabase (Postgres) - Shared Pooler
spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.dtudhbhgymaimhddyotx
spring.datasource.password=FQFqnoR17PONJji7
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

server.port=8080

# JWT
jwt.secret=cambia-esto-por-un-secreto-largo-y-aleatorio-de-al-menos-256-bits-1234567890
jwt.expiration-ms=86400000

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Logs
logging.level.org.springframework.security=TRACE

# Hikari
spring.datasource.hikari.connection-init-sql=SET search_path=public
spring.jpa.properties.hibernate.jdbc.use_get_generated_keys=false